fix pipeline pushing on dockerhub

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,8 +7,8 @@ on:
     branches: [ "main" ]
 
 env:
-  BACKEND_DOCKER_IMAGE: your-dockerhub-username/evento-backend
-  FRONTEND_DOCKER_IMAGE: your-dockerhub-username/evento-frontend
+  BACKEND_DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/evento-backend
+  FRONTEND_DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/evento-frontend
   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
@@ -48,6 +48,14 @@ jobs:
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
+      id: docker_login
+      continue-on-error: false
+
+    - name: Check Docker Login Status
+      if: steps.docker_login.outcome == 'failure'
+      run: |
+        echo "Failed to log in to Docker Hub"
+        exit 1
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
@@ -60,8 +68,6 @@ jobs:
         tags: |
           ${{ env.BACKEND_DOCKER_IMAGE }}:latest
           ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.sha }}
-        cache-from: type=registry,ref=${{ env.BACKEND_DOCKER_IMAGE }}:buildcache
-        cache-to: type=registry,ref=${{ env.BACKEND_DOCKER_IMAGE }}:buildcache,mode=max
 
     - name: Build and push Frontend
       uses: docker/build-push-action@v4
@@ -71,5 +77,3 @@ jobs:
         tags: |
           ${{ env.FRONTEND_DOCKER_IMAGE }}:latest
           ${{ env.FRONTEND_DOCKER_IMAGE }}:${{ github.sha }}
-        cache-from: type=registry,ref=${{ env.FRONTEND_DOCKER_IMAGE }}:buildcache
-        cache-to: type=registry,ref=${{ env.FRONTEND_DOCKER_IMAGE }}:buildcache,mode=max
